server:
  port: 30003
  servlet:
    context-path: /model

spring:
  application:
    name: frontstage-model
  datasource:
    url: jdbc:mysql://39.97.232.103:3306/MachineArena?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Thomas10011
    type: com.alibaba.druid.pool.DruidDataSource   #配置阿里巴巴的Druid数据源
  mvc:
    static-path-pattern: /static/**/**

eureka:
  client:
    register-with-eureka: true  #注册进Eureka
    #是否从EurekaServer抓取已有的注册信息，默认为true。
    #单节点无所谓，集群必须设为为true才能诶和ribbon使用负载均衡
    fetch-registry: true
    #入驻哪里
    service-url:
      defaultZone: http://10.10.10.208:7001/eureka
  instance:
    instance-id: frontstageModel30003
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔：默认30秒
    #    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限：默认90秒
    #    lease-expiration-duration-in-seconds: 2
