server:
  port: 10001

spring:
  application:
    name: common-algorithm
  datasource:
    url: jdbc:mysql://39.97.232.103:3306/MachineArena?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Thomas10011
    type: com.alibaba.druid.pool.DruidDataSource   #配置阿里巴巴的Druid数据源
